import QUESTIONS from '../data/questions';
import { ANSWER_CHOICES } from './constants';
import type { Difficulty, Question } from './types';

const LADDER: Difficulty[] = ['easy', 'medium', 'hard'];

/** Fisher–Yates, on a copy. */
function shuffle<T>(items: readonly T[]): T[] {
  const out = items.slice();
  for (let i = out.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

/**
 * Serves questions at a requested difficulty without repeating within a
 * session, cut down to the three LEFT/CENTER/RIGHT lanes and shuffled so the
 * correct lane is never predictable.
 *
 * Items are authored — and generated by the coach — with four options. Trimming
 * one distractor here is what let the game go to three lanes without touching
 * the question bank, the LLM schema, or the plan validator.
 */
export class QuestionManager {
  private pool: Question[];
  private used = new Set<number>();

  constructor(pool: Question[] = QUESTIONS) {
    this.pool = pool.slice();
  }

  /** The questions currently in rotation — the word-connect puzzle mines these. */
  get questions(): readonly Question[] {
    return this.pool;
  }

  /** Installs a fully validated between-level curriculum. Never called mid-round. */
  setPool(pool: readonly Question[]): void {
    if (pool.length === 0) return;
    this.pool = pool.slice();
    this.used.clear();
  }

  /**
   * @returns a question at `difficulty`, falling back to the nearest rung of
   * the ladder if that bucket is exhausted, or `null` if nothing is left.
   */
  next(difficulty: Difficulty): Question | null {
    const order = nearestFirst(difficulty);
    for (const level of order) {
      const candidates = this.pool.filter(
        (q) => q.difficulty === level && !this.used.has(q.id),
      );
      if (candidates.length > 0) {
        const picked = candidates[Math.floor(Math.random() * candidates.length)];
        this.used.add(picked.id);
        return toLaneChoices(picked);
      }
    }
    // Everything has been served — recycle so a long session never stalls.
    if (this.used.size > 0) {
      this.used.clear();
      return this.next(difficulty);
    }
    return null;
  }

  get remaining(): number {
    return this.pool.length - this.used.size;
  }

  reset(): void {
    this.used.clear();
  }
}

/** Difficulty levels ordered by distance from `difficulty`. */
function nearestFirst(difficulty: Difficulty): Difficulty[] {
  const index = LADDER.indexOf(difficulty);
  return LADDER.slice().sort(
    (a, b) => Math.abs(LADDER.indexOf(a) - index) - Math.abs(LADDER.indexOf(b) - index),
  );
}

/**
 * Keeps the correct answer plus enough randomly chosen distractors to fill the
 * lanes, then shuffles so the correct lane is never predictable. Misconception
 * labels travel with their own option, so the learner model still sees exactly
 * which wrong idea a player picked.
 */
function toLaneChoices(question: Question): Question {
  const paired = question.answers.map((text, index) => ({
    text,
    index,
    misconception: question.misconceptions?.[index],
  }));

  const correct = paired[question.correctAnswer];
  // Malformed item: leave it exactly as authored rather than invent an answer.
  if (!correct) return question;

  const distractors = shuffle(paired.filter((entry) => entry.index !== question.correctAnswer));
  const kept = shuffle([correct, ...distractors.slice(0, Math.max(0, ANSWER_CHOICES - 1))]);

  return {
    ...question,
    answers: kept.map((entry) => entry.text),
    correctAnswer: kept.findIndex((entry) => entry.index === question.correctAnswer),
    misconceptions: question.misconceptions
      ? kept.map((entry) => entry.misconception ?? 'none')
      : undefined,
  };
}
